# 一些环境

version: '3'

services:

  etcd:
    image: "quay.io/coreos/etcd:latest"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "2"
    volumes:
      - ./.docker/etcd:/default.etcd
    ports:
    - 2379:2379
    networks:
      - cago

  etcdkeeper:
    image: evildecay/etcdkeeper:latest
    environment:
      HOST: "0.0.0.0"
    ports:
    - 12000:8080
    networks:
      - cago

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"
      - "16686:16686"
    networks:
      - cago

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - cago

  # 默认账号密码:admin/admin
  # 需要自己手动添加数据源
  # 数据源地址: http://loki:3100
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./.docker/grafana:/var/lib/grafana
    networks:
      - cago

networks:
  cago:
