apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd-config.fullname" . }}
  labels:
    {{- include "etcd-config.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "etcd-config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "etcd-config.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etcd-config.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./etcdkeeper.bin", "-h", "0.0.0.0", "-p", "80", "-auth"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: etcd
          image: "{{ .Values.etcd.image.repository }}:{{ .Values.etcd.image.tag }}"
          imagePullPolicy: {{ .Values.etcd.image.pullPolicy }}
          command: ["etcd"]
          args:
            - "--name"
            - "etcd-config"
            - "--data-dir"
            - "/data"
            - "--listen-client-urls"
            - "http://0.0.0.0:2379"
            - "--advertise-client-urls"
            - "http://0.0.0.0:2379"
          ports:
            - name: etcd-2379
              containerPort: 2379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: etcd-2379
          readinessProbe:
            tcpSocket:
              port: etcd-2379
          volumeMounts:
            - mountPath: /data
              name: etcd-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: etcd-data
          emptyDir: {}
        {{- else }}
        - name: etcd-data
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-pvc
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
