basePath: /api/v1
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  user.LoginResponse:
    properties:
      username:
        description: 用户名
        type: string
    type: object
  user.LogoutResponse:
    type: object
  user.RegisterResponse:
    type: object
info:
  title: api文档
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - in: body
        name: body
        type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登录
  /user/logout:
    delete:
      consumes:
      - application/json
      description: 登出
      parameters:
      - in: body
        name: body
        type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LogoutResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登出
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - in: body
        name: body
        type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 注册
swagger: "2.0"
